<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DriverSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('drivers')->insert([
            [
                'name' => 'Budi Santoso',
                'employee_id' => 'EMP-001',
                'license_number' => '950112345678',
                'license_type' => 'A',
                'license_expiry' => '2029-05-20',
                'phone' => '081234567890',
                'region_id' => 1,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Ahmad Hidayat',
                'employee_id' => 'EMP-002',
                'license_number' => '880298765432',
                'license_type' => 'B1',
                'license_expiry' => '2028-11-12',
                'phone' => '085712345678',
                'region_id' => 2,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Joko Widodo Priyono',
                'employee_id' => 'EMP-003',
                'license_number' => '910344556677',
                'license_type' => 'B2',
                'license_expiry' => '2030-01-15',
                'phone' => '081399887766',
                'region_id' => 2,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Dedi Kurniawan',
                'employee_id' => 'EMP-004',
                'license_number' => '850411223344',
                'license_type' => 'A',
                'license_expiry' => '2027-08-09',
                'phone' => '082144332211',
                'region_id' => 1,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Rian Hidayatullah',
                'employee_id' => 'EMP-005',
                'license_number' => '970566778899',
                'license_type' => 'B1',
                'license_expiry' => '2029-03-24',
                'phone' => '087855667788',
                'region_id' => 1,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Siti Nurjanah (Driver VIP)',
                'employee_id' => 'EMP-006',
                'license_number' => '940612131415',
                'license_type' => 'A',
                'license_expiry' => '2031-07-19',
                'phone' => '081122334455',
                'region_id' => 1,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Agus Setyawan',
                'employee_id' => 'EMP-007',
                'license_number' => '890745464748',
                'license_type' => 'B1',
                'license_expiry' => '2028-04-02',
                'phone' => '085299001122',
                'region_id' => 1,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Hendra Wijaya',
                'employee_id' => 'EMP-008',
                'license_number' => '920877889900',
                'license_type' => 'A',
                'license_expiry' => '2029-10-10',
                'phone' => '081288776655',
                'region_id' => 2,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'M. Rizky Saputra',
                'employee_id' => 'EMP-009',
                'license_number' => '990922334455',
                'license_type' => 'B2',
                'license_expiry' => '2030-12-25',
                'phone' => '081311223344',
                'region_id' => 2,
                'status' => 'available',
                'is_active' => true,
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'name' => 'Eko Prasetyo',
                'employee_id' => 'EMP-010',
                'license_number' => '871055667788',
                'license_type' => 'A',
                'license_expiry' => '2027-02-28',
                'phone' => '085644556677',
                'region_id' => 1,
                'status' => 'available',
                'is_active' => false,
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}