<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VehicleSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('vehicles')->insert([
            [
                'plate_number' => 'B 1234 PQA',
                'brand' => 'Toyota',
                'model' => 'Avanza 1.3 G',
                'year' => 2021,
                'type' => 'angkutan_orang',
                'ownership' => 'milik',
                'fuel_type' => 'bensin',
                'capacity' => 7,
                'current_km' => 34200,
                'region_id' => 1,
                'status' => 'available',
                'notes' => 'Servis rutin berkala aman.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'B 8821 UYT',
                'brand' => 'Mitsubishi',
                'model' => 'L300 Pick Up',
                'year' => 2019,
                'type' => 'angkutan_barang',
                'ownership' => 'milik',
                'fuel_type' => 'solar',
                'capacity' => 2,
                'current_km' => 78900,
                'region_id' => 1,
                'status' => 'available',
                'notes' => 'AC kurang dingin, perlu dicek.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'D 3044 ABC',
                'brand' => 'Hino',
                'model' => 'Dutro 130 HD',
                'year' => 2022,
                'type' => 'angkutan_barang',
                'ownership' => 'sewa',
                'fuel_type' => 'solar',
                'capacity' => 8,
                'current_km' => 45100,
                'region_id' => 2,
                'status' => 'available',
                'notes' => 'Pajak hidup sampai Desember.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'L 4920 UX',
                'brand' => 'Isuzu',
                'model' => 'Elf Giga',
                'year' => 2020,
                'type' => 'angkutan_barang',
                'ownership' => 'milik',
                'fuel_type' => 'solar',
                'capacity' => 5,
                'current_km' => 62300,
                'region_id' => 2,
                'status' => 'available',
                'notes' => 'Kondisi ban belakang baru.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'B 2210 SJD',
                'brand' => 'Daihatsu',
                'model' => 'Gran Max Blind Van',
                'year' => 2023,
                'type' => 'angkutan_barang',
                'ownership' => 'milik',
                'fuel_type' => 'bensin',
                'capacity' => 1,
                'current_km' => 12500,
                'region_id' => 1,
                'status' => 'available',
                'notes' => 'Unit baru operasional kurir.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'H 9311 OP',
                'brand' => 'Toyota',
                'model' => 'Innova Reborn',
                'year' => 2020,
                'type' => 'angkutan_orang',
                'ownership' => 'milik',
                'fuel_type' => 'solar',
                'capacity' => 7,
                'current_km' => 55000,
                'region_id' => 1,
                'status' => 'available',
                'notes' => 'Khusus operasional direksi.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'B 7741 KLO',
                'brand' => 'Suzuki',
                'model' => 'Carry Pick Up',
                'year' => 2018,
                'type' => 'angkutan_barang',
                'ownership' => 'sewa',
                'fuel_type' => 'bensin',
                'capacity' => 1,
                'current_km' => 98200,
                'region_id' => 1,
                'status' => 'available',
                'notes' => 'Kaki-kaki agak berisik.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'D 1195 VBN',
                'brand' => 'Honda',
                'model' => 'Mobilio E',
                'year' => 2019,
                'type' => 'angkutan_orang',
                'ownership' => 'milik',
                'fuel_type' => 'bensin',
                'capacity' => 7,
                'current_km' => 67000,
                'region_id' => 2,
                'status' => 'available',
                'notes' => 'Baru selesai ganti oli.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'L 5088 AA',
                'brand' => 'Mitsubishi',
                'model' => 'Fuso Canter',
                'year' => 2021,
                'type' => 'angkutan_barang',
                'ownership' => 'milik',
                'fuel_type' => 'solar',
                'capacity' => 10,
                'current_km' => 39000,
                'region_id' => 2,
                'status' => 'available',
                'notes' => 'Uji KIR baru diperpanjang.',
                'created_at' => now(), 'updated_at' => now(),
            ],
            [
                'plate_number' => 'B 9012 XYZ',
                'brand' => 'Hyundai',
                'model' => 'Staria',
                'year' => 2022,
                'type' => 'angkutan_orang',
                'ownership' => 'sewa',
                'fuel_type' => 'solar',
                'capacity' => 9,
                'current_km' => 21000,
                'region_id' => 1,
                'status' => 'available',
                'notes' => 'Unit sewa VIP tamu.',
                'created_at' => now(), 'updated_at' => now(),
            ],
        ]);
    }
}